// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schronisko;

namespace Schronisko.Migrations
{
    [DbContext(typeof(DogeContext))]
    partial class DogeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Schronisko.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfWows");

                    b.Property<int?>("OgonId");

                    b.HasKey("DogId");

                    b.HasIndex("OgonId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("Schronisko.Models.Ogon", b =>
                {
                    b.Property<int>("OgonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.HasKey("OgonId");

                    b.ToTable("Ogons");
                });

            modelBuilder.Entity("Schronisko.Dog", b =>
                {
                    b.HasOne("Schronisko.Models.Ogon", "Ogon")
                        .WithMany()
                        .HasForeignKey("OgonId");
                });
#pragma warning restore 612, 618
        }
    }
}
